### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/custom-addons#324]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] astikar_custom
- [ ] avanzosc_custom
- [ ] bainu_custom
- [ ] be_custom
- [ ] ccg_custom
- [ ] cinetronica_custom
- [ ] customer_invoice_personalized_report
- [ ] ds_custom
- [ ] galaxia_custom
- [ ] hispaled_custom
- [ ] igalia_custom
- [ ] pesa_custom
- [ ] picking_a5_landscape_report
- [ ] purchase_order_custom_report
- [ ] rockbotic_custom
- [ ] rockbotic_website_crm
- [ ] sale_order_custom_report
- [ ] trukebai
- [ ] tumaker_custom
- [ ] tumaker_picking_report
- [ ] ubar_custom
